### ISSUE TITLE
python 3 full not working

### ISSUE THREAD

**Issue by jshaffstall** [anvil-works/routing#29]
**Describe the bug**
I have a hash based routing example app that I migrated to use this routing.  It all works great when running the app from the base URL.  But when I try to go directly to a form using that form's route, I get the following error in the logs:

```
SyntaxError: invalid syntax (history.py, line 1)
at /downlink/anvil/history.py, line 1
```

The app I converted was pre-layouts, and as part of adding the routing dependency, the app was upgraded for layouts.    I'm also using the `TemplateWithContainerRoute` since the app I'm migrating used templates.

This doesn't happen with the example M3 based app, so it might very well be something boneheaded I've done during the migration, but I'm not seeing anything.

**Version**
The latest master.

**To Reproduce**
Go to: https://dtcvv32xon5ief24.anvil.app/debug/23LB67SX66FHPDU5JYKDFNF23DCIVQ5R%3DZZQ6DR2JFMQID5TJNLEL7FWE/about

Here's the clone link for the app: https://anvil.works/build#clone:DTCVV32XON5IEF24=TAI5S6GFWVB64I75SCXVQKZW

**Comment by s-cork** [comment]
If you switch to python 3.10 on the server it should work
We'll get that fixed in python 3 full

**Comment by jshaffstall** [comment]
Thanks!  I'd forgotten that app was old enough to predate the Python 3.10 server runtime that's the default now.

**Comment by s-cork** [comment]
this should now be fixed

**Comment by s-cork** [comment]
just looking at the app - would recommend turning your links into `routing.NavLink` components

**Comment by jshaffstall** [comment]
Thanks, I'll add that to the list.  This was practice migrating an old hash routing example to the new routing.  I'll add NavLinks to the todo list.

Another thing that gave me some  pause that you might want to document is the environment the routing methods run in.  I'd been going to do an authorization check in a before_load method and force the user to login if they weren't already, but then realized that when they go directly to a URL that probably runs on the server.  Sticking a print(is_server_side()) in before_load it looks like the initial run is on the server, and then another happens on the client.

I'm assuming the best practice is to redirect in before_load, rather than do anything that relies on the client-side environment.

**Comment by s-cork** [comment]
yes moved to #30 

correct - before load was designed with redirects in mind
although - maybe that'd work with an `is_server_side` check

Best practices are up for grabs
