### ISSUE TITLE
Can't catch NotFound error

### ISSUE THREAD

**Issue by yahiakala** [anvil-works/routing#53]
**Describe the bug**
I navigate to a route that doesn't exist, and I get the NotFound error raised. This is fine, but I can't catch the error in a try except block.

I have tried:

except router.NotFound
except Exception

**Version**
v0.3.2

**Additional context**
I can avoid the error using a NotFoundRoute with default_not_found but I want to catch this error and do more specific things depending on which form.

**I am considering making a PR for this issue**
No

**Comment by s-cork** [comment]
Where are you trying to catch it?

Maybe we need a handler rather than a form.

**Comment by yahiakala** [comment]
I have a try except block in one of my client code forms:

```
    try:
        router.navigate('/route1')
    except Exception:
        do_something
```

The exception is not caught, and the exception is still raised.

**Comment by s-cork** [comment]
Obviously that wouldn't scale across the application since it wouldn't account for a user just visiting /route1 by changing the address bar. I'll have a think about possible solutions.

**Comment by yahiakala** [comment]
I'm fine with not catching the exception raised when the user visits /route1 by typing in the address bar. 

My use case is that I have routes defined in a dependency app (open source version of a SaaS app) and want to do some different behaviour if it is running standalone vs as a dependency.

Generally, the not found route is fine, I like the idea of a 404 page for example. But I do want to define exceptions to it.

Perhaps it would be more elegant to avoid this issue altogether and find another way to change my app's behaviour in these two circumstances, without a try-except block on the routes themselves. I'll look into that.

**Comment by s-cork** [comment]
Ok. I'm not sure I follow exactly what you'd want to do in the except block here?

**Comment by yahiakala** [comment]
In my case I'd want to do nothing (pass). The full use case is quite elaborate and the more I think on it, the less I think this try-except block would be helpful. I'm going in a different direction.

If you want to address this issue I can leave it open, otherwise I can close it.
